import { Metadata } from "next";
import NotFoundPage from "../not-found";

export default function VerifyEmail() {
  return <NotFoundPage />;
}

export const metadata: Metadata = {
  title: "Verify Email",
  description: "Generated by create next app",
};
