import { Footer } from "@/components/common";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "List Booking",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      {children}
      <Footer className="block xl:hidden" />
    </>
  );
}
