export const PATH_API = {
  SET_TOKEN: "/api/set-token",
  DELETE_TOKEN: "/api/delete-token",
  GET_TOKEN: "/api/get-token",
  REGISTER: "/auth/register",
  LOGIN: "/auth/login",
  LOGOUT: "/auth/logout",
  FORGOT_PASSWORD: "/users/forgot-password",
  VERIFY_FORGOT_PASSWORD: "/users/verify-forgot-password",
  RESET_PASSWORD: "/users/reset-password",
  CHANGE_PASSWORD: "/users/change-password",
  REFRESH_TOKEN: "/auth/refresh-token",
  GET_PROFILE: "/users/me",
  VERIFY_EMAIL: "/users/verify-email",
  RESEND_VERIFY_EMAIL: "/users/resend-verify-email",
  UPDATE_PROFILE: "/users/me",
  UPLOAD_IMAGE: "/medias/upload-image",
  GET_LIST_HOTEL: "/hotels",
  GET_HOTEL_DETAILS: "/hotels/:hotelId",
} as const;
