import { Header } from '@/components';
import type { Metadata } from 'next';
import { DM_Sans } from 'next/font/google';
import { twMerge } from 'tailwind-merge';
import './globals.scss';

export const dmSans = DM_Sans({
  weight: ['700', '600', '500', '400'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Trip Guide',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={twMerge(dmSans.className, 'text-black44')}>
        <Header />
        {children}
      </body>
    </html>
  );
}
