import { Header } from '@/components/common';
import type { Metadata } from 'next';
import { DM_Sans } from 'next/font/google';
import { twMerge } from 'tailwind-merge';
import './globals.scss';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

export const dmSans = DM_Sans({
  weight: ['700', '600', '500', '400'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Trip Guide',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={twMerge(dmSans.className, 'text-black44 bg-grayAFB')}>
        <ToastContainer />
        <Header />
        {children}
      </body>
    </html>
  );
}
