import { ExploreWorldSection } from "@/components/flight";
import {
  BestPlaceSection,
  FeaturedDestinationsSection,
  TrendCitiesSection,
} from "@/components/hotel";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Flight Booking",
  description: "Generated by create next app",
};

interface FlightPageProps {}

export default function FlightPage(props: FlightPageProps) {
  return (
    <div className="flex flex-col gap-[70px] bg-grayFB pt-[124px] dark:bg-black">
      <BestPlaceSection />
      <FeaturedDestinationsSection />
      <TrendCitiesSection className="xl:py-[94px]" />
      <ExploreWorldSection />
    </div>
  );
}
