import { CarHero } from '@/components/car';
import { Footer, NavbarFilter } from '@/components/common';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Car Rental',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <CarHero>
        <NavbarFilter type="car" />
      </CarHero>
      {children}
      <Footer />
    </>
  );
}
